### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by lazywei** [brainfoolong/bomnibox#7]
Hi,

Normally, when typing something (text, custom search, url), Chrome's behavior is

(0) Enter -> use current tab for the new content
(1) CMD+Enter (on Mac) -> use new tab for the new content

Yet somehow this behavior is not work when using bomnibox (i.e., use `$` for searching).
Is this expected or unexpected?

Thanks

**Comment by brainfoolong** [comment]
Seems unexpected, the onInputEntered receive a type on how the user want to open the suggested url. I simply ignore it currently, never thought about that.
https://developer.chrome.com/extensions/omnibox#event-onInputEntered
I'll do that fix soon.

**Comment by brainfoolong** [comment]
Should be fixed in master. Can you test it if this work as you have expected it?

**Comment by lazywei** [comment]
It seems it is still not work.

**Comment by brainfoolong** [comment]
Hm, i've tried it with ALT + Open in Windows than it opens in a new tab. Otherwise it opens in the same tab. Does this not work on a MAC?

**Comment by lazywei** [comment]
Hmm, OK, ALT+Enter works, but the convention in Mac should be CMD+Enter I guess. Is it possible to make it aware of the OS? Well done :+1:

**Comment by brainfoolong** [comment]
Hm, i've commited one more try, check it out. If it work, ok, otherwise there is no chance to make it working because this looks like a chrome issue. The `onInputEntered` listener return a type with 3 possible values `"currentTab", "newForegroundTab", or "newBackgroundTab"`. What type is returned is interpreted by chrome and i cannot modify it or detected what keys are pressed currently in the omnibox.

**Comment by lazywei** [comment]
great, it works!

**Comment by brainfoolong** [comment]
Oh, cool :) I'll close this now. Chrome webstore release will follow in the next days. Have a nice weekend.
